services:
   board-db:
      extends:
         file: common.yml
         service: base-postgres
      hostname: board-db
      container_name: board-db
      ports:
         - '5432:5432'
      env_file:
         - ./services/board-service/.env.prod
      volumes:
         - ./docker-data/db/board:/var/lib/postgresql/data
      networks:
         - board-db-net
         - pgadmin-net

   board-service:
      build:
         dockerfile: Dockerfile.prod
         context: services/board-service
      container_name: board-service
      ports:
         - '8001:8001'
      restart: on-failure
      depends_on:
         board-db:
            condition: service_healthy
      env_file:
         - ./services/board-service/.env.prod
      networks:
         - board-db-net
