services:
   board-db:
      image: postgres:latest
      restart: on-failure
      hostname: board-db
      container_name: board-db
      ports:
         - '5432:5432'
      env_file:
         - .env.prod
      volumes:
         - ./docker-data/db/board:/var/lib/postgresql/data
